### ISSUE TITLE
Payload Example: UI HTML is not Valid

### ISSUE THREAD

**Issue by BlazeFace** [hytopiagg/sdk#6]
https://github.com/hytopiagg/sdk/blob/32ba0fafd21f798915c0ff70d659077944895f09/examples/payload-game/assets/ui/index.html#L1

Because the tag is closed on line 1 there in an unbalanced tag on the last line.

**Comment by BlazeFace** [comment]
After removing the extra tag the ui overlay is also blocking interactivity

**Comment by iamarkdev** [comment]
Should be resolved now, if interactivity is still blocked, what browser are you using?

**Comment by BlazeFace** [comment]
It looks like it works on chromium but still fails on firefox!

**Comment by iamarkdev** [comment]
Noted thanks, probably an issue with synthetic events or frame message passing. Will get it resolved

**Comment by iamarkdev** [comment]
Resolved, we moved to injected div approach in the client.
